name: CI Workflow for Arpna Blog Post

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd arpna-react-app
        npm install

    - name: Run Tests
      run: |
        cd arpna-react-app
        npm test

    - name: Build Project
      run: |
        cd arpna-react-app
        npm run build
